### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by vaisajuh** [jonthus/ot-harjoitustyo#1]
<strong>Projekti ladattu 10.12.2021 klo 18.00</strong>

Moi!

Alkuun pitää todeta, että mielenkiintoinen aihe konaisuudessaan. Vaatimusmäärittelyssä oli hyvin selkeästi kuvattu projektin tarkoitus, ja odotetusta sisällöstä oli hyvin kattava kuvaus. Seuraavaksi omia huomiota ja parannusehdotuksia projektiin liittyen.

Ohjelmannan käynnistykessä oli ongelmia ja komento <strong>poetry run invoke start</strong> tuotti seuraavanlaisen virheen:
![image](https://user-images.githubusercontent.com/81490976/145689079-c7167e56-4666-4054-a55a-95ffb38b76af.png)

Ajaessani komennon <strong>poetry run invoke test</strong> tuli seuravaalainen virhe:

![image](https://user-images.githubusercontent.com/81490976/145689061-10e97661-675b-4f82-8e50-af7c803341af.png)

Tulosteiden mukaan virheet liittyvät samaan Bio-moduulin, jota ei löytynyt ajon aikana. Yritin asentaa Biopythonin uusimman version, mutta sain silti saman virheilmoituksen. Tietysti ongelma on omissa säädöissä, mutta mielestäni olisi hyvä mainita, että jos tarvitsee asennella uusia pakatteja ohjelman ajamiseen.

Komento <strong>poetry invoke lint</strong> herjasi myös moduulin pylab puuttumisesta, jota en myöskään näin äkkiseltään saanut korjattua. Muutenkin pylintin mukaan koodissa olisi useammassa kohdassa korjattavaa, mutta nämä ovat helppoja korjattavia. Hyvä työkalu koodin korjaamiseen on autopep8-kirjasto, joka kannattaa mielestäni ottaa käyttöön.

Luokkajako näyttää järkevältä, mutta mielestäni luokkia voisi sijoitella omiin kansioihinsa selkeyttämään sovelluksen työnjakoa. Esimerkiksi käyttöliittymästä ja sovelluslogiikasta vastaavat luokat voisi laittaa molemmat omiin kansioihinsa. Tekstiedostot voisivat myös olla sijoitettuna omaan kansioihinsa, ja voisiko näitä samoja tiedostoja käyttää myös testeissä, että ei erikseen luoda testeille omia tekstitiedostoja?

Luokka gc_content vaikuttaa selkeältä ja hyvin loogisesti rakennetulta. Kuitenkin jos single responsibility periaatetta noudatettaisiin, niin luokka palauttaisi arvon, ja tulostaminen toteutettaisiin käyttöliittymässä. Tässä mielessä metodin run olisi mielestäni voinut jättää pois.

Luokka sequence vaikuttaa myös loogiselta, mutta  luokan toiminta ei ihan täysin avautunut itselleni ilman, että olisi voinut käyttää ohjelmaa. Tässä mielestäni kuitenkin kyseessä sama kuin luokan gc_contentin tapauksessa, että tulostus olisi tarkoitus tehdä käyttöliittymässä.

Yhteenvetona voisi todeta, että ihan hyvää tekemistä. Koodi vaikuttaa hyvin loogiselta ja rakenne järkevältä. Tietysti se vähän hankaloittaa asiaa, että en saanut ajettua ohjelmaa, mutta muuten näyttäsi olevan moni asia kunnossa. Tiettyjä asioita voisi mielestäni vielä parantaa, ja niistä olenkin maininnut. Mukavaa joulunodotusta!

**Comment by jonthus** [comment]
Kiitos kommenteista!
